apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insight-service
  template:
    metadata:
      labels:
        app: insight-service
    spec:
      containers:
        - name: insight-service
          image: aron918/insight-service-tele-insight-capstone-project:b276971be48e12f4e59b40db0600615d231f4244
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATA_REST_BASE_PATH
              value: /api/v1/auth
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://insight-db-svc:5432/tele_insight_blog_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials-secret
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials-secret
                  key: postgres-password
            - name: SERVER_PORT
              value: "8082"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://service-discovery:8761/eureka/